apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: raasbridge-validator-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: raasbridge-validator
  minReplicas: 3
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
